const MESSAGE = {
    REGISTER_SUCCESSFULLY: "registration successfully",
    USER_NAME_EXIST:"username already exist",
    INVALID_CREDENTIALS:"invalid credentials",
    SERVER_ERROR:"something went wrong",
    USER_NOT_FOUND:"user not found",
    LOGIN_SUCCESSFULLY:"login successfully",
    PROFILE_UPDATED:"profile updated successfully",
    USER_RECORD_DELETED:"deleted successfully",
    ORG_ADD_SUCCESSFULLY:"organization add successfully",
    ORG_NOT_ADD:"organization not add",
    ORGANIZATION_LIST :"all organization list",
    VALIDATION_ERROR:"please field all data",
    PASSWORD_NOT_UPDATE:"can't update password",
    NOT_UPDATE:"can't update",
    ORGANIZATION_UPDATED:"organization updated",
    ORGANIZATION_NOT_UPDATED:"orgainzation not updated",
    EMAIL_ERROR :"email already exist",
    REGISTER_FAILED:"registeration failed",
    NOT_ALLOWED:"not allowed",
    PROFILE:"here your profile",
    MAIl_NOT_SENT :"mail not sent",
    EMAIL_SENT_SUCCESSFULLY:"email sent successfully"
  };
  export default MESSAGE